// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Les migrations (DDL) doivent passer par la connexion directe, pas par le pooler
    // (PgBouncer en mode transaction casse les verrous que Prisma utilise pour les migrations).
    // L'application elle-même continue d'utiliser DATABASE_URL (poolée) via src/lib/prisma.ts.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
